// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// count_bins
NumericVector count_bins(NumericVector counts, NumericVector bins);
RcppExport SEXP ghelper_count_bins(SEXP countsSEXP, SEXP binsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bins(binsSEXP);
    __result = Rcpp::wrap(count_bins(counts, bins));
    return __result;
END_RCPP
}
